# Generated by Django 2.1.2 on 2018-10-23 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(default='grant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(default='', max_length=100)),
                ('top_crew', models.CharField(default=['', '', '', '', ''], max_length=400)),
                ('top_cast', models.CharField(default=['', '', '', '', ''], max_length=400)),
                ('back_image', models.CharField(default='https://via.placeholder.com/150x350', max_length=100)),
                ('poster_path', models.CharField(default='https://via.placeholder.com/150x350', max_length=100)),
                ('featured_image', models.CharField(default='https://via.placeholder.com/350x150', max_length=100)),
                ('content_image_1', models.CharField(default='https://via.placeholder.com/350x150', max_length=100)),
                ('content_image_2', models.CharField(default='https://via.placeholder.com/350x150', max_length=100)),
                ('tagline', models.CharField(default='', max_length=100)),
                ('overview', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('crew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.Crew')),
            ],
            bases=('movies.crew',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('crew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.Crew')),
            ],
            bases=('movies.crew',),
        ),
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Collection'),
        ),
        migrations.AddField(
            model_name='category',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
